### Tensor

In [1]:
from __future__ import print_function
import torch
import seaborn as sns

uninitialized matrix 

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


random initialized matrix

In [3]:
x = torch.randn(100,3)
# print(x)

### Autograd

In [4]:
x.grad_fn is None

True

In [5]:
x.requires_grad

False

In [6]:
import torch

In [7]:
x = torch.ones(2, 2, requires_grad=True)


In [8]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [9]:
print(y.grad_fn)

In [10]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [11]:
out.backward(torch.tensor(1.))

In [12]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [13]:
x = torch.randn(3, requires_grad=True)

In [14]:
x

tensor([ 0.9371, -1.8498,  0.8131], requires_grad=True)

In [15]:
x.shape

torch.Size([3])

In [16]:
y = x * 2

In [17]:
y

tensor([ 1.8742, -3.6997,  1.6262], grad_fn=<MulBackward0>)

In [18]:
while y.norm() < 1000:
    y = y * 2
    
print(y)

tensor([ 479.7848, -947.1127,  416.2954], grad_fn=<MulBackward0>)


In [19]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


### Neural Networks

In [20]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [21]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[-0.1240,  0.0513, -0.0045, -0.1310,  0.0943, -0.0842, -0.0619, -0.0010,
          0.1088, -0.0509]], grad_fn=<AddmmBackward>)


In [22]:
net.zero_grad()
out.backward(torch.randn(1, 10))

In [21]:
params = list(net.parameters())

In [ ]:
params

In [ ]:
python.__